### ISSUE TITLE
SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by hanecak** [soit-sk/slovakia_parliament#1]
Scraper prestal po case fungovat a aktualne hlasi:

```
SyntaxError: 'return' outside function
```

**Comment by hanecak** [comment]
OK, pull request #2 chybu opravil.

Poznamka: Ale mame iny problem: z webu NR SR sa vytratili samotne textove prepisy - vid #4.

**Comment by katkad** [comment]
tento bug bol opraveny tymto https://github.com/soit-sk/slovakia_parliament/commit/4734532d5175b63a17c3fa7202e6a00d5f3db445
